test:
  base_url: "https://test.service.tib.eu/renate/server/api/"
  endpoints:
    collections: "core/collections"
    collection_items: "discover/search/objects?scope="
    items: "core/items"
    update_item_metadata: "core/items/{item_uuid}"
    upload_bitstreams: "core/bundles/{bundle_uuid}/bitstreams"
    "login": "authn/login"
    "GROBID_URL": "http://localhost:8070/api/processFulltextDocument"    
  credentials:
    user: ""
    password: ""

production:
  base_url: "https://oa.tib.eu/renate/server/api/"
  endpoints:
    collections: "core/collections"
    collection_items: "discover/search/objects?scope="
    items: "core/items"
    update_item_metadata: "core/items/{item_uuid}"
    upload_bitstreams: "core/bundles/{bundle_uuid}/bitstreams"
    "login": "authn/login"
    "GROBID_URL": "http://localhost:8070/api/processFulltextDocument"
  credentials:
    user: ""
    password: ""
